### ISSUE TITLE
Bug with potions durations bonus

### ISSUE THREAD

**Issue by Pexep** [Archy-X/AuraSkills#193]
### Server software and version

Beta 1.3.19

### Expected behavior

1. The alchemist bonus
alchemist ability should encrase the duration of potions, splash potions and lingering potions we brew.

2. The splasher bonus
splasher ability should encrase the duration of splash potions for each player affected.

### Actual behavior

1. The alchemist bonus

- For normal potions : it works corectly. 
- For splash potions : it doesn't work totally, the player who throw the potion doesn't get the entire bonus (only 75% of the bonus sees during tests). On other players, the bonus is given entirely. (these tests were performed with the splasher ability disabled)
- For lingering potions : it doesn't work. The bonus is given to no one.

2. The splasher bonus
The thrower duration has no sens : 

- when the thrower is alone, the bonus is correctly given (based on the broken alchemist bonus for splash on oneself)
- when the thrower is not alone, the potion duration is correct for other players. For the thrower, the duration is never the same and is never correct.

### How to reproduce

1. The alchemist bonus 

- Disable the splasher ability
- Brew normal potions, splash potions and lingering potions
- Try on yourself and on other players the different potions. Look at the durations

2. The splasher bonus

- Enable the splasher ablility
- Try on yourself and with other players. See the difference on you.

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment]
The vanilla mechanics for splash potions mean that you don't get the entire duration most of the time because it's scaled down based on the distance from where the potion splashes to the player's head. You can only get the full duration if the splash potion lands directly on the top of a player's head.

Testing myself, the duration bonus was properly applied with Splasher on a speed splash potion (Alchemy 20 vs Alchemy 1). Also, lingering potions aren't mentioned in the Splasher description so it's intended that the Splasher duration bonus doesn't apply to lingering potions.

The only bug I think is valid is that Alchemist doesn't apply to lingering potions.
